version: "3.9"

services:
  app:
    build:
      context: ./django_truckapp
      args:
       - DEV=true
    ports:
      - "8020:8020"
    volumes:
      - ./django_truckapp:/django_truckapp
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver_plus 0.0.0.0:8020 --cert-file ssl/cert.pem --key-file ssl/key.pem"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=maris
      - DB_PASS=bv4811ss
    networks:
      - truckapp-network
    depends_on:
      - db

  vue:
    build:
      context: ./vue_truckapp
      args:
        - DEV=true
    command: npm run serve
    ports:
      - "8025:8025"
    volumes:
      - ./vue_truckapp:/vue_truckapp
      - /vue_truckapp/node_modules
    depends_on:
      - app
    networks:
      - truckapp-network

  db:
    image: postgres:16-alpine3.18
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=maris
      - POSTGRES_PASSWORD=bv4811ss
    networks:
      - truckapp-network

volumes:
  dev-db-data:

networks:
  truckapp-network:
    external: true
