version: "3.9"

services:
  app:
    build:
      context: ./django_truckapp
      args:
       - DEV=true
    ports:
      - "8020:8020"
    volumes:
      - ./django_truckapp:/django_truckapp
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8020"
